import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import '../assets/styles/globals.css'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

const comfortaa = Comfortaa({
  subsets: ['latin'],
  variable: '--font-comfortaa',
  weight: ['300', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${comfortaa.variable} mx-auto max-w-[1850px] antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
